### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by DDAAAA123** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#101]
Loading aborted due to error reloading workflow data

TypeError: Cannot read properties of undefined (reading 'type')
TypeError: Cannot read properties of undefined (reading 'type')
    at e.onConnectionsChange (http://127.0.0.1:8188/extensions/ComfyUI-Easy-Use/assets/extensions-29B2pS6_.js:1:100022)
    at e.configure (http://127.0.0.1:8188/assets/index-CoOvI8ZH.js:29240:35)
    at LGraph2.configure (http://127.0.0.1:8188/assets/index-CoOvI8ZH.js:39063:17)
    at LGraph$1.configure (http://127.0.0.1:8188/assets/index-CoOvI8ZH.js:88029:26)
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/assets/index-CoOvI8ZH.js:88529:18)
    at async app.loadGraphData (http://127.0.0.1:8188/extensions/ComfyUI-Manager/components-manager.js:773:9)
    at async loadWorkflow (http://127.0.0.1:8188/assets/index-CoOvI8ZH.js:88218:11)
    at async ComfyApp.setup (http://127.0.0.1:8188/assets/index-CoOvI8ZH.js:88225:12)
    at async http://127.0.0.1:8188/assets/GraphView-BW5soyxY.js:3931:7
This may be due to the following script:
/extensions/ComfyUI-Easy-Use/assets/extensions-29B2pS6_.js

**Comment by AlekPet** [comment]
Hi. You provided the code, but there is no mention of my extension, you should contact the creator of the extension https://github.com/yolain/ComfyUI-Easy-Use , as I see only him, I do not use this extension, so it is difficult to answer.

**Comment by DDAAAA123** [comment]
![Snipaste_2024-12-13_17-07-42](https://github.com/user-attachments/assets/af0d825c-274d-473f-8856-fb0c9e3f6d6e)
The workflow requires a missing detection plug-in AlekPet, but I don't know what the problem is

**Comment by DDAAAA123** [comment]
> 你好。你提供了代码，但没有提到我的扩展，你应该联系扩展的创建者https://github.com/yolain/ComfyUI-Easy-Use，因为我只看到他，我没有使用这个扩展，所以很难回答。

![Snipaste_2024-12-13_17-07-42](https://github.com/user-attachments/assets/adbe5504-87bf-40f7-b89d-a1455497ced3)
The workflow requires a missing detection plug-in AlekPet, but I don't know what the problem is

**Comment by AlekPet** [comment]
Show all terminal log

**Comment by DDAAAA123** [comment]
> 显示所有终端日志

I:\ComfyUI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-14 10:16:52.568323
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: I:\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI
** Log path: I:\ComfyUI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   4.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12282 MB, total RAM 65405 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\web
[ComfyUI-Easy-Use] server: v1.2.5 Loaded
[ComfyUI-Easy-Use] web root: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
Total VRAM 12282 MB, total RAM 65405 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
### Loading: ComfyUI-Impact-Pack (V8.0.1)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Impact-Subpack (V1.0)
### Loading: ComfyUI-Manager (V2.55.4)
### ComfyUI Version: v0.3.7-18-g3dfdddc | Released on '2024-12-11'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
--------------
 ### Mixlab Nodes: Loaded
ChatGPT.available False
edit_mask.available True
## clip_interrogator_model not found: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\clip_interrogator\Salesforce\blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
## text_generator_model not found: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\prompt_generator\text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
## zh_en_model not found: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\prompt_generator\opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
ffmpeg could not be found. Using ffmpeg from imageio-ffmpeg.
TripoSR.available
MiniCPMNode.available
Scenedetect.available
FishSpeech.available
SenseVoice.available
Whisper.available False
fal-client## OK
FalVideo.available
 --------------
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
### [START] ComfyUI AlekPet Nodes v1.0.37 ###
Node -> ChatGLMNode: ChatGLM4TranslateCLIPTextEncodeNode, ChatGLM4TranslateTextNode, ChatGLM4InstructNode, ChatGLM4InstructMediaNode [Loading]
Node -> ArgosTranslateNode: ArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode [Loading]
Node -> DeepTranslatorNode: DeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode [Loading]
Node -> GoogleTranslateNode: GoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode [Loading]
Node -> PoseNode: PoseNode [Loading]
Node -> ExtrasNode: PreviewTextNode, HexToHueNode, ColorsCorrectNode [Loading]
Node -> IDENode: IDENode [Loading]
Node -> PainterNode: PainterNode [Loading]
### [END] ComfyUI AlekPet Nodes ###
Traceback (most recent call last):
  File "I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\__init__.py", line 275, in <module>
    from .ArgosTranslateNode.argos_translate_node import (
  File "I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\ArgosTranslateNode\argos_translate_node.py", line 5, in <module>
    import argostranslate.translate
  File "I:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\argostranslate\translate.py", line 5, in <module>
    import ctranslate2
  File "I:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ctranslate2\__init__.py", line 8, in <module>
    import pkg_resources
  File "I:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

Cannot import I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet module for custom nodes: module 'pkgutil' has no attribute 'ImpImporter'
# 😺dzNodes: LayerStyle -> Cannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to https://github.com/chflame163/ComfyUI_LayerStyle/issues/5

[rgthree-comfy] Loaded 42 extraordinary nodes. 🎉

WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 219 nodes successfully.

        "The purpose of art is washing the dust of daily life off our souls." - Pablo Picasso


Import times for custom nodes:
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Batch-Condition-ComfyUI
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light
   0.0 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle
   0.1 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SAM2
   0.1 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.4 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Detail-Daemon
   0.5 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.5 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.6 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet
   0.8 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack
   1.3 seconds (IMPORT FAILED): I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
   1.8 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   4.9 seconds: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes

Starting server

To see the GUI go to: http://127.0.0.1:8188
I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js
I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css
FETCH DATA from: I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js
I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css
I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/model-viewer.min.js
I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
I:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
[]
[]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json [DONE]

**Comment by AlekPet** [comment]
This is a problem with argostranslate, there was already a question https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/100 or if you don't need this node, you can disable these nodes https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/93#issuecomment-2480928680

**Comment by AlekPet** [comment]
This is a problem with argostranslate, there was already a question https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/100 or if you don't need this node, you can disable these nodes https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/93#issuecomment-2480928680
