### ISSUE TITLE
Cannot load alekpet in ubuntu and ComfyUI

### ISSUE THREAD

**Issue by mobile-163** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#103]
In ubuntu OS，i activate conda using 'conda create -n ComfyUI python=3.9 -y && conda activate ComfyUI'.
After that, i git clone alekpet from this node of github.  But ComfyUI cannot load alekpet node.   It report in ComfyUI procecee like below.  Pl help to solve this issue.  TKS!
![image](https://github.com/user-attachments/assets/797aaa1a-169d-48ef-ae2e-156eee24de44)

**Comment by mobile-163** [comment]
### [START] ComfyUI AlekPet Nodes v1.0.37 ###
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/root/miniconda3/envs/ComfyUI/lib/python3.9/site-packages/aiohttp/connector.py", line 1109, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
  File "/root/miniconda3/envs/ComfyUI/lib/python3.9/site-packages/aiohappyeyeballs/impl.py", line 123, in start_connection
    raise OSError(first_errno, msg)
ConnectionRefusedError: [Errno 111] Multiple exceptions: [Errno 111] Connect call failed ('0.0.0.0', 443), [Errno 111] Connect call failed ('::', 443, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ComfyUI/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/ComfyUI/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/root/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Manager-main/glob/manager_server.py", line 1373, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
  File "/root/miniconda3/envs/ComfyUI/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/envs/ComfyUI/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/root/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Manager-main/glob/manager_server.py", line 1370, in default_cache_update
    await asyncio.gather(a, b, c, d, e)
  File "/root/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Manager-main/glob/manager_server.py", line 1357, in get_cache
    json_obj = await core.get_data(uri, True)
  File "/root/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Manager-main/glob/manager_core.py", line 657, in get_data
    async with session.get(uri) as resp:
  File "/root/miniconda3/envs/ComfyUI/lib/python3.9/site-packages/aiohttp/client.py", line 1423, in __aenter__
    self._resp: _RetType = await self._coro
  File "/root/miniconda3/envs/ComfyUI/lib/python3.9/site-packages/aiohttp/client.py", line 701, in _request
    conn = await self._connector.connect(
  File "/root/miniconda3/envs/ComfyUI/lib/python3.9/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/root/miniconda3/envs/ComfyUI/lib/python3.9/site-packages/aiohttp/connector.py", line 1050, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/root/miniconda3/envs/ComfyUI/lib/python3.9/site-packages/aiohttp/connector.py", line 1394, in _create_direct_connection
    raise last_exc
  File "/root/miniconda3/envs/ComfyUI/lib/python3.9/site-packages/aiohttp/connector.py", line 1363, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/root/miniconda3/envs/ComfyUI/lib/python3.9/site-packages/aiohttp/connector.py", line 1124, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [Multiple exceptions: [Errno 111] Connect call failed ('0.0.0.0', 443), [Errno 111] Connect call failed ('::', 443, 0, 0)]
Node -> ChatGLMNode: ChatGLM4TranslateCLIPTextEncodeNode, ChatGLM4TranslateTextNode, ChatGLM4InstructNode, ChatGLM4InstructMediaNode [Loading] 
Node -> DeepTranslatorNode: DeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode [Loading] 
Node -> ArgosTranslateNode: ArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode [Loading] 
Node -> GoogleTranslateNode: GoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode [Loading] 
Node -> PoseNode: PoseNode [Loading] 
Node -> ExtrasNode: PreviewTextNode, HexToHueNode, ColorsCorrectNode [Loading] 
Node -> IDENode: IDENode [Loading] 
Node -> PainterNode: PainterNode [Loading] 
### [END] ComfyUI AlekPet Nodes ###
Traceback (most recent call last):
  File "/root/ComfyUI/ComfyUI/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/ComfyUI/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet-master/__init__.py", line 288, in <module>
    from .GoogleTranslateNode.google_translate_node import (
  File "/root/ComfyUI/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet-master/GoogleTranslateNode/google_translate_node.py", line 6, in <module>
    from googletrans import Translator, LANGUAGES
  File "/root/miniconda3/envs/ComfyUI/lib/python3.9/site-packages/googletrans/__init__.py", line 7, in <module>
    from googletrans.client import Translator
  File "/root/miniconda3/envs/ComfyUI/lib/python3.9/site-packages/googletrans/client.py", line 22, in <module>
    from googletrans.models import Translated, Detected, TranslatedPart
  File "/root/miniconda3/envs/ComfyUI/lib/python3.9/site-packages/googletrans/models.py", line 25, in <module>
    class Translated(Base):
  File "/root/miniconda3/envs/ComfyUI/lib/python3.9/site-packages/googletrans/models.py", line 42, in Translated
    parts: List[TranslatedPart] | None,
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'

Cannot import /root/ComfyUI/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet-master module for custom nodes: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'

Import times for custom nodes:
   0.0 seconds: /root/ComfyUI/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /root/ComfyUI/ComfyUI/custom_nodes/AIGODLIKE-COMFYUI-TRANSLATION
   0.1 seconds: /root/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Manager-main
   0.3 seconds (IMPORT FAILED): /root/ComfyUI/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet-master

Starting server

To see the GUI go to: http://0.0.0.0:8188

**Comment by mobile-163** [comment]
Yes, I consider it is version problem for python. 
I will create conda virtual environment using python=3.10 and pip install requirement.txt . Hope solve it.
Tks
