### ISSUE TITLE
PainterNode - 404 not found errors

### ISSUE THREAD

**Issue by niklasreinmuth** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#104]
Hey AlekPet, I just installed your extension and when I'm loading a Painternode, I get two pop ups for 404 - not found in my browser. This also happens whenever I'm drawing something. Here's two screenshots along with the console log. Any idea what could be the issue?

![image](https://github.com/user-attachments/assets/09d81567-965a-4042-9adc-71827704191f)
![image](https://github.com/user-attachments/assets/8a4067bb-cec7-47b4-8267-77fe8823239f)

Console Output:
```
20:28:15.913 [Warning] [ComfyUI-0/STDOUT] Traceback (most recent call last):
20:28:15.913 [Warning] [ComfyUI-0/STDOUT]   File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 327, in execute
20:28:15.913 [Warning] [ComfyUI-0/STDOUT]     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
20:28:15.913 [Warning] [ComfyUI-0/STDOUT]   File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 202, in get_output_data
20:28:15.913 [Warning] [ComfyUI-0/STDOUT]     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
20:28:15.913 [Warning] [ComfyUI-0/STDOUT]   File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 174, in _map_node_over_list
20:28:15.913 [Warning] [ComfyUI-0/STDOUT]     process_inputs(input_dict, i)
20:28:15.913 [Warning] [ComfyUI-0/STDOUT]   File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 163, in process_inputs
20:28:15.913 [Warning] [ComfyUI-0/STDOUT]     results.append(getattr(obj, func)(**inputs))
20:28:15.913 [Warning] [ComfyUI-0/STDOUT]   File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\PainterNode\painter_node.py", line 279, in painter_execute
20:28:15.913 [Warning] [ComfyUI-0/STDOUT]     i = Image.open(image_path)
20:28:15.913 [Warning] [ComfyUI-0/STDOUT]   File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\PIL\Image.py", line 3431, in open
20:28:15.913 [Warning] [ComfyUI-0/STDOUT]     fp = builtins.open(filename, "rb")
20:28:15.913 [Warning] [ComfyUI-0/STDOUT] FileNotFoundError: [Errno 2] No such file or directory: 'D:\\StabilityMatrix-win-x64\\Data\\Packages\\ComfyUI\\input\\Paint_10.png'
20:28:15.913 [Warning] [ComfyUI-0/STDOUT] 
```

**Comment by AlekPet** [comment]
Hi. I don't know, maybe something has changed in comfyui in terms of saving files and what is this ComfyBackendDirect (extension??), I need to look.

**Comment by AlekPet** [comment]
Update version my extension! Updated!

**Comment by niklasreinmuth** [comment]
It's working! Thank you very much! 😊
