### ISSUE TITLE
proxy_ssl_contest cannot improt 

### ISSUE THREAD

**Issue by aierbaipang** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#13]
Traceback (most recent call last):
  File "D:\ProgramData\ComfyUI\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ProgramData\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\__init__.py", line 169, in <module>
    installNodes()
  File "D:\ProgramData\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\__init__.py", line 167, in installNodes
    addComfyUINodesToMapping(nodeElement)
  File "D:\ProgramData\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\__init__.py", line 126, in addComfyUINodesToMapping
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ProgramData\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\TranslateNode\translate_node.py", line 8, in <module>
    translator = Translator()
  File "D:\ProgramData\ComfyUI\python_embeded\lib\site-packages\googletrans\client.py", line 37, in __init__
    self.client = httpx.Client(http2=http2)
  File "D:\ProgramData\ComfyUI\python_embeded\lib\site-packages\httpx\_client.py", line 682, in __init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[BaseTransport]] = {
  File "D:\ProgramData\ComfyUI\python_embeded\lib\site-packages\httpx\_client.py", line 685, in <dictcomp>
    else self._init_proxy_transport(
  File "D:\ProgramData\ComfyUI\python_embeded\lib\site-packages\httpx\_client.py", line 739, in _init_proxy_transport
    return HTTPTransport(
  File "D:\ProgramData\ComfyUI\python_embeded\lib\site-packages\httpx\_transports\default.py", line 149, in __init__
    self._pool = httpcore.HTTPProxy(
TypeError: HTTPProxy.__init__() got an unexpected keyword argument 'proxy_ssl_context'

Cannot import D:\ProgramData\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet module for custom nodes: HTTPProxy.__init__() got an unexpected keyword argument 'proxy_ssl_context'

please help me

**Comment by AlekPet** [comment]
try removing the old module like this:
1. Go to __ComfyUI\python_embeded__ folder and run shell (windows: up line where path, input cmd, and press enter, open cmd shell)
2. Input this, you see install comflyui modules (find googletrans or googletrans-py)
```
python.exe -m pip list
```
3. Uninstall them:
```
python.exe -m pip uninstall googletrans googletrans-py
```
Confirm uninstall, enter "Y".
4. After run comflyui, he must install googletrans-py.

> If that doesn't work, do the following:
1. Аollow the steps above 1-3
2. Go to where install my nodes ComfyUI_Custom_Nodes_AlekPet then in folder TranslateNode, and edit file requirements.txt as below.
```
#git+https://github.com/StarkBotsIndustries/googletrans.git
#If googletrans-py cannot be installed, use the GitHub installation method mentioned above.
googletrans==3.1.0a0
deep-translator==1.11.4
```
3. Save changes
4. Run comflyui, this install module googletrans ver.3.1.0a0
5. Test =)

**Comment by aierbaipang** [comment]
thanks ，very nice!!!!

**Comment by Natotela** [comment]
had the same trouble, thanks for shooting
