### ISSUE TITLE
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'

### ISSUE THREAD

**Issue by kookoolive** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#31]
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'

**Comment by walala** [comment]
the same error.

### [START] ComfyUI AlekPet Nodes ###
Node -> ArgosTranslateNode [Loading]
Node -> ExtrasNode [Loading]
Node -> PainterNode [Loading]
Node -> PoseNode [Loading]
Node -> TranslateNode [Loading]
Traceback (most recent call last):
  File "D:\ai\ComfyUI\nodes.py", line 1814, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\__init__.py", line 223, in <module>
    installNodes()
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\__init__.py", line 219, in installNodes
    addComfyUINodesToMapping(nodeElement)
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\__init__.py", line 167, in addComfyUINodesToMapping
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\TranslateNode\translate_node.py", line 4, in <module>
    from googletrans import Translator, LANGUAGES
  File "C:\Users\Staff\AppData\Local\Programs\Python\Python39\lib\site-packages\googletrans\__init__.py", line 7, in <module>
    from googletrans.client import Translator
  File "C:\Users\Staff\AppData\Local\Programs\Python\Python39\lib\site-packages\googletrans\client.py", line 22, in <module>
    from googletrans.models import Translated, Detected, TranslatedPart
  File "C:\Users\Staff\AppData\Local\Programs\Python\Python39\lib\site-packages\googletrans\models.py", line 25, in <module>
    class Translated(Base):
  File "C:\Users\Staff\AppData\Local\Programs\Python\Python39\lib\site-packages\googletrans\models.py", line 42, in Translated
    parts: List[TranslatedPart] | None,
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'

Cannot import D:\ai\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet module for custom nodes: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'

Import times for custom nodes:
   2.0 seconds (IMPORT FAILED): D:\ai\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet

Starting server

To see the GUI go to: http://127.0.0.1:8188

Thanks so much in advance!

**Comment by hheavenknowss** [comment]
it's may occur with python==3.8, upgreed python version to 3.10 may fix

**Comment by walala** [comment]
OMG, as you said, after changing to python 3.10, the problem was solved, thank you very much.

**Comment by AlekPet** [comment]
The topic is closed because the issue has been resolved.
