### ISSUE TITLE
AttributeError: 'ComfyUIManagerLogger' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by nogutsnoglorious** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#41]
```
[2024-03-13 18:35] ### Loading: ComfyUI-Manager (V2.9)
[2024-03-13 18:35] ### ComfyUI Revision: 2045 [b7b55931] | Released on '2024-03-04'
[2024-03-13 18:36] [1;35m### [START] ComfyUI AlekPet Nodes ###[0m
[2024-03-13 18:36] [92mNode -> ArgosTranslateNode [Loading][0m
[2024-03-13 18:36] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2024-03-13 18:36] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2024-03-13 18:36] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-03-13 18:36] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-03-13 18:36] Traceback (most recent call last):
  File "D:\AI\ComfyUI\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\__init__.py", line 144, in <module>
    installNodes()
  File "D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\__init__.py", line 139, in installNodes
    addComfyUINodesToMapping(nodeElement)
  File "D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\__init__.py", line 76, in addComfyUINodesToMapping
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\ArgosTranslateNode\argos_translate_node.py", line 8, in <module>
    import argostranslate.translate
  File "D:\AI\ComfyUI\python_embeded\Lib\site-packages\argostranslate\translate.py", line 7, in <module>
    import stanza
  File "D:\AI\ComfyUI\python_embeded\Lib\site-packages\stanza\__init__.py", line 1, in <module>
    from stanza.pipeline.core import DownloadMethod, Pipeline
  File "D:\AI\ComfyUI\python_embeded\Lib\site-packages\stanza\pipeline\core.py", line 17, in <module>
    from stanza.models.common.doc import Document
  File "D:\AI\ComfyUI\python_embeded\Lib\site-packages\stanza\models\common\doc.py", line 19, in <module>
    from stanza.models.constituency import tree_reader
  File "D:\AI\ComfyUI\python_embeded\Lib\site-packages\stanza\models\constituency\tree_reader.py", line 16, in <module>
    tqdm = get_tqdm()
           ^^^^^^^^^^
  File "D:\AI\ComfyUI\python_embeded\Lib\site-packages\stanza\utils\get_tqdm.py", line 34, in get_tqdm
    if sys.stderr is not None and sys.stderr.isatty():
                                  ^^^^^^^^^^^^^^^^^
AttributeError: 'ComfyUIManagerLogger' object has no attribute 'isatty'
[2024-03-13 18:36] 
[2024-03-13 18:36] Cannot import D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet module for custom nodes: 'ComfyUIManagerLogger' object has no attribute 'isatty'
[2024-03-13 18:36] 
Import times for custom nodes:
[2024-03-13 18:36]    0.4 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-03-13 18:36]   10.7 seconds (IMPORT FAILED): D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
[2024-03-13 18:36] 
[2024-03-13 18:36] Starting server
[2024-03-13 18:36] 
[2024-03-13 18:36] To see the GUI go to: http://127.0.0.1:8188
[2024-03-13 18:36] FETCH DATA from: D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

```

Greetings! How to fix this error?

**Comment by AlekPet** [comment]
Hi, try deleting or moving the ArgosTranslate folder, I just don’t know what other extensions you have. I'll have to take a look, maybe I need to reinstall ArgosTrranlsate. I launched it today, everything was ok, what operating system do you have?

**Comment by nogutsnoglorious** [comment]
Removing the folder worked.
