### ISSUE TITLE
(IMPORT FAILED) error occured

### ISSUE THREAD

**Issue by ellyoun13** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#42]
2.8 seconds (IMPORT FAILED): E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
 
 Import times for custom nodes:
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\example_node.py copy.py
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\image-resize-comfyui
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-Yolov8
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Selector
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SimpleMath
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Filters
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hangover-Moondream
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\StableZero123-comfyui
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-lama-remover
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Dave_CustomNode
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-popup_preview
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\hd_node
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\steerable-motion
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyQR-scanning-nodes
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OpenPose-Editor
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyQR
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Allor
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds (IMPORT FAILED): E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OOTDiffusion
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.1 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.1 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.2 seconds (IMPORT FAILED): E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_OOTDiffusion_CXH
   0.2 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_GLM4Node
   0.3 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.4 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
   0.5 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.6 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   0.7 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   2.1 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   2.6 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack
   2.8 seconds (IMPORT FAILED): E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
   2.9 seconds: E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything

Starting server

I

**Comment by darkalfx** [comment]
I'm also getting the same error on the latest version of Comfy:
`(IMPORT FAILED): D:\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet`

So nothing works

**Comment by AlekPet** [comment]
Hello, there is no information about the error, only that the import was unsuccessful, is there any other information, maybe you have the latest version of Python?

see here: https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/37

**Comment by darkalfx** [comment]
After further testing, it looks like there's a conflict between your package and ComfyUI-Manager which prevents this package from loading? 

```
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\stanza\utils\get_tqdm.py", line 34, in get_tqdm
    if sys.stderr is not None and sys.stderr.isatty():
                                  ^^^^^^^^^^^^^^^^^
AttributeError: 'ComfyUIManagerLogger' object has no attribute 'isatty'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet module for custom nodes: 'ComfyUIManagerLogger' object has no attribute 'isatty
```

However if I remove ComfyUI-Manager then the package loads fine

**Comment by AlekPet** [comment]
> After further testing, it looks like there's a conflict between your package and ComfyUI-Manager which prevents this package from loading? 
> 
> ```
> File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\stanza\utils\get_tqdm.py", line 34, in get_tqdm
>     if sys.stderr is not None and sys.stderr.isatty():
>                                   ^^^^^^^^^^^^^^^^^
> AttributeError: 'ComfyUIManagerLogger' object has no attribute 'isatty'
> 
> Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet module for custom nodes: 'ComfyUIManagerLogger' object has no attribute 'isatty'
> ```
> 
> However if I remove ComfyUI-Manager then the package loads fine, I am unsure which package needs fixing

here: https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/43

**Comment by alexbofa** [comment]
https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/43#issuecomment-2002369467

**Comment by dydwgmcnl4241** [comment]
the same error

**Comment by dydwgmcnl4241** [comment]
> Hello, there is no information about the error, only that the import was unsuccessful, is there any other information, maybe you have the latest version of Python?
> 
> see here: #37

I met the same error. and I use python 3.10

**Comment by AlekPet** [comment]
> > Hello, there is no information about the error, only that the import was unsuccessful, is there any other information, maybe you have the latest version of Python?
> > 
> > see here: #37
> 
> I met the same error. and I use python 3.10
> 
> 
> (IMPORT FAILED) AlekPet/ComfyUI_Custom_Nodes_AlekPet  
> 
> Nodes: PoseNode, PainterNode, TranslateTextNode, TranslateCLIPTextEncodeNode, DeepTranslatorTextNode, DeepTranslatorCLIPTextEncodeNode, ArgosTranslateTextNode, ArgosTranslateCLIPTextEncodeNode, PreviewTextNode.NOTE: Due to the dynamic nature of node name definitions, ComfyUI-Manager cannot recognize the node list from this extension. The Missing nodes and Badge features are not available for this extension.
> 
> NOTE: Due to the dynamic nature of node name definitions, ComfyUI-Manager cannot recognize the node list from this extension. The Missing nodes and Badge features are not available for this extension.
Note this is not an error, it’s just that the manager cannot determine the name of the nodes, because  For me they are not registered directly in the NODE_CLASS_MAPPINGS dictionary, but are added dynamically.

**Comment by dydwgmcnl4241** [comment]
> > > Hello, there is no information about the error, only that the import was unsuccessful, is there any other information, maybe you have the latest version of Python?
> > > see here: #37
> > 
> > 
> > I met the same error. and I use python 3.10
> > (IMPORT FAILED) AlekPet/ComfyUI_Custom_Nodes_AlekPet
> > Nodes: PoseNode, PainterNode, TranslateTextNode, TranslateCLIPTextEncodeNode, DeepTranslatorTextNode, DeepTranslatorCLIPTextEncodeNode, ArgosTranslateTextNode, ArgosTranslateCLIPTextEncodeNode, PreviewTextNode.NOTE: Due to the dynamic nature of node name definitions, ComfyUI-Manager cannot recognize the node list from this extension. The Missing nodes and Badge features are not available for this extension.
> > NOTE: Due to the dynamic nature of node name definitions, ComfyUI-Manager cannot recognize the node list from this extension. The Missing nodes and Badge features are not available for this extension.
> 
> Note this is not an error, it’s just that the manager cannot determine the name of the nodes, because For me they are not registered directly in the NODE_CLASS_MAPPINGS dictionary, but are added dynamically.

got it, but how can I fix this problem?

**Comment by AlekPet** [comment]
> NODE_CLASS_MAPPINGS

I could make them not dynamic, but simply registered directly in the dictionary, just like I did, the manager searches for NODE_CLASS_MAPPINGS and takes the keys with the names of the nodes and displays them where the Nodes field is in the manager and controls them, turn them on, off, etc. .

**Comment by boytjj** [comment]
pip installed torchmetrics-1.2.1

**Comment by maiqunshan** [comment]
Traceback (most recent call last):
  File "C:\ComfyUI_MAI\ComfyUI\nodes.py", line 2024, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_MAI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet-master\__init__.py", line 185, in <module>
    installNodes()
  File "C:\ComfyUI_MAI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet-master\__init__.py", line 181, in installNodes
    addComfyUINodesToMapping(nodeElement)
  File "C:\ComfyUI_MAI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet-master\__init__.py", line 129, in addComfyUINodesToMapping
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_MAI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet-master\TranslateNode\translate_node.py", line 2, in <module>
    from googletrans import Translator, LANGUAGES
  File "C:\ComfyUI_MAI\python_embeded\Lib\site-packages\googletrans\__init__.py", line 6, in <module>
    from googletrans.client import Translator
  File "C:\ComfyUI_MAI\python_embeded\Lib\site-packages\googletrans\client.py", line 25, in <module>
    class Translator:
  File "C:\ComfyUI_MAI\python_embeded\Lib\site-packages\googletrans\client.py", line 55, in Translator
    proxies: typing.Dict[str, httpcore.SyncHTTPTransport] = None, timeout: Timeout = None):
AttributeError: module 'httpcore' has no attribute 'SyncHTTPTransport'

Cannot import C:\ComfyUI_MAI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet-master module for custom nodes: module 'httpcore' has no attribute 'SyncHTTPTransport'
