### ISSUE TITLE
Can anyone solve the problem for me?

### ISSUE THREAD

**Issue by departurechen** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#75]
Collecting argostranslate
  Using cached argostranslate-1.9.6-py3-none-any.whl.metadata (10 kB)
Collecting ctranslate2<5,>=4.0 (from argostranslate)
  Using cached ctranslate2-4.3.1-cp311-cp311-win_amd64.whl.metadata (10 kB)
Exception in thread Thread-11 (information):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "D:\ComfyUI\ComfyUI进阶整合包（含汉化补丁与常用自定义节点）\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\__init__.py", line 63, in information
    for info in datas:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xab in position 82: illegal multibyte sequence

**Comment by AlekPet** [comment]
Hi, I would suggest that the code does not like your path to comfyui containing non-latin characters. You can also try changing my `__init__.py`

This line 62:
```py
def information(datas):
    for info in datas:
        if not DEBUG:
            print(info, end="\r", flush=True)
```
on
```py
def information(datas):
    pass
```

**Comment by departurechen** [comment]
Thanks，problem solved
