### ISSUE TITLE
 module 'pkgutil' has no attribute 'ImpImporter'

### ISSUE THREAD

**Issue by lindongyue7** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#79]
Traceback (most recent call last):
  File "D:\comfyui\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\comfyui\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\__init__.py", line 275, in <module>
    from .ArgosTranslateNode.argos_translate_node import (
  File "D:\comfyui\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\ArgosTranslateNode\argos_translate_node.py", line 5, in <module>
    import argostranslate.translate
  File "C:\Users\PC\miniconda3\Lib\site-packages\argostranslate\translate.py", line 5, in <module>
    import ctranslate2
  File "C:\Users\PC\miniconda3\Lib\site-packages\ctranslate2\__init__.py", line 8, in <module>
    import pkg_resources
  File "C:\Users\PC\miniconda3\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

Cannot import D:\comfyui\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet module for custom nodes: module 'pkgutil' has no attribute 'ImpImporter'

**Comment by AlekPet** [comment]
Hi, I looked at the log, you have miniconda installed, although modules should be searched in comfyui's own python_embeded environment (if you installed the portable version of confyui https://github.com/comfyanonymous/ComfyUI/releases/download/v0.1.2/ComfyUI_windows_portable_nvidia.7z). Try updating your python version (for conda `conda update python` for Windows https://www.python.org/downloads/), and also reinstall argostranslate manually (in the console `pip uninstall argostranslate` or if you have conda `conda uninstall argostranslate`.

**Comment by ethanryannn** [comment]
![AlekPet](https://github.com/user-attachments/assets/18a91b6a-fc4c-4970-ac96-9b48b7810d95)
Hi, Alek, I get the same error [Import Failed] these days. I am using the latest version of ComfyUI v0.2.7 and latest pip 24.3.1. I recently uninstalled my anaonconda, idk for some reasons, your node just not work.
