### ISSUE TITLE
I was unable to load the plug-in node in comfyui

### ISSUE THREAD

**Issue by heytony965342** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#93]
After I installed it according to the documentation, I was unable to load the plug-in node in comfyui.
cd comfyui/custom_nodes/
git clone https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet.git
After restarting comfyui, the plug-in node was not loaded, and it was displayed in ComfyUI-Manager
(IMPORT FAILED) AlekPet/ComfyUI_Custom_Nodes_AlekPet.
The environment I used is:
ubuntu 24.04
python 3.12.7
comfyui updated to the latest version

**Comment by AlekPet** [comment]
Hi. There are no errors in these logs, show the entire log and terminal. The problem may be in your Python version, a similar problem has already been encountered in questions, as an option, replace the __init__.py file and download config.json (from here https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/tree/new_init_config_disabled ) and try to disable node folders in it (start with argos or google)

**Comment by heytony965342** [comment]
Thank you very much. The solution you suggested temporarily solved my problem of not being able to use this plug-in.

**Comment by AlekPet** [comment]
> Thank you very much. The solution you suggested temporarily solved my problem of not being able to use this plug-in.

Hi, show the full log of the comfyui window so that we can determine the cause of the problem, maybe the necessary dependencies were not installed.

**Comment by wwwffbf** [comment]
> > Thank you very much. The solution you suggested temporarily solved my problem of not being able to use this plug-in.
> 
> Hi, show the full log of the comfyui window so that we can determine the cause of the problem, maybe the necessary dependencies were not installed.

I encountered the same problem on windows platform with the latest version of comfyui 0.2.7, replacing init.py and config.json by your method solves the problem, here is the error report of the problem:

`### [START] ComfyUI AlekPet Nodes v1.0.33 ###
Node -> ChatGLMNode: ChatGLM4TranslateCLIPTextEncodeNode, ChatGLM4TranslateTextNode [Loading]
Node -> ArgosTranslateNode: ArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode [Loading]
Node -> DeepTranslatorNode: DeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode [Loading]
Node -> GoogleTranslateNode: GoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode [Loading]
Node -> PoseNode: PoseNode [Loading]
Node -> ExtrasNode: PreviewTextNode, HexToHueNode, ColorsCorrectNode [Loading]
Node -> IDENode: IDENode [Loading]
Node -> PainterNode: PainterNode [Loading]
Collecting argostranslate
  Using cached argostranslate-1.9.6-py3-none-any.whl.metadata (10 kB)
Collecting googletrans-py
  Using cached googletrans-py-4.0.0.tar.gz (12 kB)
  Installing build dependencies: started
Collecting sacremoses==0.0.53 (from argostranslate)
  Using cached sacremoses-0.0.53.tar.gz (880 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [31 lines of output]
  Traceback (most recent call last):
    File "E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
      backend = _build_backend()
                ^^^^^^^^^^^^^^^^
    File "E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
      obj = import_module(mod_path)
            ^^^^^^^^^^^^^^^^^^^^^^^
    File "importlib\__init__.py", line 90, in import_module
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 995, in exec_module
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
      import setuptools.version
    File "E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\version.py", line 1, in <module>
      import pkg_resources
    File "E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
      register_finder(pkgutil.ImpImporter, find_on_path)
                      ^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [31 lines of output]
  Traceback (most recent call last):
    File "E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
      backend = _build_backend()
                ^^^^^^^^^^^^^^^^
    File "E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
      obj = import_module(mod_path)
            ^^^^^^^^^^^^^^^^^^^^^^^
    File "importlib\__init__.py", line 90, in import_module
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 995, in exec_module
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
      import setuptools.version
    File "E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\version.py", line 1, in <module>
      import pkg_resources
    File "E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
      register_finder(pkgutil.ImpImporter, find_on_path)
                      ^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
### [END] ComfyUI AlekPet Nodes ###
Traceback (most recent call last):
  File "E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2024, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\__init__.py", line 275, in <module>
    from .ArgosTranslateNode.argos_translate_node import (
  File "E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\ArgosTranslateNode\argos_translate_node.py", line 4, in <module>
    import argostranslate.package
ModuleNotFoundError: No module named 'argostranslate'

Cannot import E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet module for custom nodes: No module named 'argostranslate'`

**Comment by AlekPet** [comment]
Try installing argostranslate manually:
Inside directory `E:\SDiff\ComfyUI_v027\ComfyUI_windows_portable\` run shell and check argostranslate installed:
```bash
.\python_embeded\python.exe -m pip list
```

If not install:
```bash
.\python_embeded\python.exe -m pip install argostranslate
```
or uninstal and install again
```bash
.\python_embeded\python.exe -m pip uninstall argostranslate
.\python_embeded\python.exe -m pip install argostranslate
```
and check...

**Comment by AlekPet** [comment]
module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
https://stackoverflow.com/a/77364602/23512000
