### ISSUE TITLE
Missing Node Types, When loading the graph, the following node types were not found: DeepTranslatorTextNode

### ISSUE THREAD

**Issue by hoonkies** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#94]
I can't use alekpet node, please help me figure out what's going on. This happened since I installed some python dependencies yesterday. “Missing Node Types, When loading the graph, the following node types were not found: DeepTranslatorTextNode”

/Users/Park/miniconda3/bin/python3 "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/main.py" 
(base) park@Parks-Office-MacBook-Pro ~ % /Users/Park/miniconda3/bin/python3 "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/main.py" 
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-19 18:11:48.766854
** Platform: Darwin
** Python version: 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 08:22:19) [Clang 14.0.6 ]
** Python executable: /Users/Park/miniconda3/bin/python3
** ComfyUI Path: /Volumes/SSD 980 1TB/stable-diffusion-comfyui
** Log path: /Users/Park/comfyui.log
Comfy Pets is not up to date. Pulling latest changes...
已经是最新的。
Comfy Pets repository is up to date.

Prestartup times for custom nodes:
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/rgthree-comfy
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-Easy-Use
   0.4 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-Manager
   1.6 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-Pets

Total VRAM 32768 MB, total RAM 32768 MB
pytorch version: 2.4.1
Set vram state to: SHARED
Device: mps
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
[Prompt Server] web root: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/web
Adding extra search path checkpoints /Volumes/SSD 980 1TB/stable-diffusion-webui/models/Stable-diffusion
Adding extra search path configs /Volumes/SSD 980 1TB/stable-diffusion-webui/models/Stable-diffusion
Adding extra search path vae /Volumes/SSD 980 1TB/stable-diffusion-webui/models/VAE
Adding extra search path loras /Volumes/SSD 980 1TB/stable-diffusion-webui/models/Lora
Adding extra search path loras /Volumes/SSD 980 1TB/stable-diffusion-webui/models/LyCORIS
Adding extra search path upscale_models /Volumes/SSD 980 1TB/stable-diffusion-webui/models/ESRGAN
Adding extra search path upscale_models /Volumes/SSD 980 1TB/stable-diffusion-webui/models/RealESRGAN
Adding extra search path upscale_models /Volumes/SSD 980 1TB/stable-diffusion-webui/models/SwinIR
Adding extra search path embeddings /Volumes/SSD 980 1TB/stable-diffusion-webui/embeddings
Adding extra search path hypernetworks /Volumes/SSD 980 1TB/stable-diffusion-webui/models/hypernetworks
Adding extra search path controlnet /Volumes/SSD 980 1TB/stable-diffusion-webui/extensions/sd-webui-controlnet/models
/Users/Park/miniconda3/lib/python3.12/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
FaceDetailer: Model directory already exists
FaceDetailer: Model already exists
Total VRAM 32768 MB, total RAM 32768 MB
pytorch version: 2.4.1
Set vram state to: SHARED
Device: mps
/Users/Park/miniconda3/lib/python3.12/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
### ComfyUI Revision: 2821 [8a528100] | Released on '2024-11-10'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
/Users/Park/miniconda3/lib/python3.12/site-packages/albumentations/__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.21 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
[ReActor] - STATUS - Running v0.5.1-b2 in ComfyUI
Traceback (most recent call last):
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/nodes.py", line 2018, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-reactor-node/__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-reactor-node/nodes.py", line 27, in <module>
    from scripts.reactor_faceswap import (
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-reactor-node/scripts/reactor_faceswap.py", line 14, in <module>
    from scripts.reactor_swapper import (
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-reactor-node/scripts/reactor_swapper.py", line 25, in <module>
    from scripts.r_faceboost import swapper, restorer
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-reactor-node/scripts/r_faceboost/restorer.py", line 17, in <module>
    from r_basicsr.utils.registry import ARCH_REGISTRY
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-reactor-node/r_basicsr/__init__.py", line 3, in <module>
    from .archs import *
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-reactor-node/r_basicsr/archs/__init__.py", line 16, in <module>
    _arch_modules = [importlib.import_module(f'r_basicsr.archs.{file_name}') for file_name in arch_filenames]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Park/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-reactor-node/r_basicsr/archs/swinir_arch.py", line 11, in <module>
    from .arch_util import to_2tuple, trunc_normal_
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-reactor-node/r_basicsr/archs/arch_util.py", line 6, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'

Cannot import /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-reactor-node module for custom nodes: No module named 'distutils'
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: CoreMLExecutionProvider, AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
[Crystools INFO] Crystools version: 1.21.0
[Crystools INFO] CPU: Apple M2 Max - Arch: arm64 - OS: Darwin 24.1.0
[Crystools ERROR] Could not init pynvml (Nvidia).NVML Shared Library Not Found
[Crystools WARNING] No GPU with CUDA detected.
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
--------------
 ### Mixlab Nodes: Loaded
json_repair## OK
ChatGPT.available True
edit_mask.available True
## clip_interrogator_model not found: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/models/clip_interrogator/Salesforce/blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
## zh_en_model not found: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/models/prompt_generator/opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
TripoSR.available
MiniCPMNode.available
Scenedetect.available
FishSpeech.available
SenseVoice.available
Whisper.available False
fal-client## OK
FalVideo.available
 -------------- 
WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 219 nodes successfully.

	"Art is the universal language that transcends boundaries and speaks to all." - Unknown

[rgthree-comfy] Loaded 42 epic nodes. 🎉

### Loading: ComfyUI-Impact-Pack (Subpack: V0.8)
[Impact Pack] Wildcards loading done.
[ComfyUI-Easy-Use] server: v1.2.5 Loaded
[ComfyUI-Easy-Use] web root: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-Easy-Use/web_version/v2 Loaded
[comfyui_controlnet_aux] | INFO -> Using ckpts path: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
Please 'pip install xformers'
Nvidia APEX normalization not installed, using PyTorch LayerNorm
Please 'pip install xformers'
Nvidia APEX normalization not installed, using PyTorch LayerNorm
Traceback (most recent call last):
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/nodes.py", line 2018, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI_HF_Servelress_Inference/__init__.py", line 9, in <module>
    from .nodes.Joy_Caption import JoyPipeline, Joy_caption, Joy_caption_load
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI_HF_Servelress_Inference/nodes/Joy_Caption.py", line 25
    return model_checkpoint
IndentationError: unexpected indent

Cannot import /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI_HF_Servelress_Inference module for custom nodes: unexpected indent (Joy_Caption.py, line 25)
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Please 'pip install xformers'
Nvidia APEX normalization not installed, using PyTorch LayerNorm
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
### [START] ComfyUI AlekPet Nodes v1.0.33 ###
Node -> ChatGLMNode: ChatGLM4TranslateCLIPTextEncodeNode, ChatGLM4TranslateTextNode [Loading] 
Node -> ArgosTranslateNode: ArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode [Loading] 
Node -> GoogleTranslateNode: GoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode [Loading] Node -> DeepTranslatorNode: DeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode [Loading] 

Node -> PoseNode: PoseNode [Loading] 
Node -> ExtrasNode: PreviewTextNode, HexToHueNode, ColorsCorrectNode [Loading] 
Node -> IDENode: IDENode [Loading] 
Node -> PainterNode: PainterNode [Loading] 
### [END] ComfyUI AlekPet Nodes ###
Traceback (most recent call last):
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/nodes.py", line 2018, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI_Custom_Nodes_AlekPet/__init__.py", line 275, in <module>
    from .ArgosTranslateNode.argos_translate_node import (
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI_Custom_Nodes_AlekPet/ArgosTranslateNode/argos_translate_node.py", line 5, in <module>
    import argostranslate.translate
  File "/Users/Park/miniconda3/lib/python3.12/site-packages/argostranslate/translate.py", line 7, in <module>
    import stanza
  File "/Users/Park/miniconda3/lib/python3.12/site-packages/stanza/__init__.py", line 1, in <module>
    from stanza.pipeline.core import Pipeline
  File "/Users/Park/miniconda3/lib/python3.12/site-packages/stanza/pipeline/core.py", line 13, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'

Cannot import /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI_Custom_Nodes_AlekPet module for custom nodes: No module named 'distutils'
Traceback (most recent call last):
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/nodes.py", line 2018, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-art-venture/__init__.py", line 13, in <module>
    from .modules.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-art-venture/modules/nodes.py", line 12, in <module>
    from .utility_nodes import (
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-art-venture/modules/utility_nodes.py", line 17, in <module>
    from .utils import pil2tensor, tensor2pil, ensure_package, get_dict_attribute
  File "/Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-art-venture/modules/utils.py", line 9, in <module>
    import pkg_resources
  File "/Users/Park/miniconda3/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

Cannot import /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-art-venture module for custom nodes: module 'pkgutil' has no attribute 'ImpImporter'
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...

Import times for custom nodes:
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/websocket_image_save.py
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-Molmo
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-Miaoshouai-Tagger
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/cg-use-everywhere
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/stability-ComfyUI-nodes
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-Florence-2
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI_ADV_CLIP_emb
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-YOLO
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/masquerade-nodes-comfyui
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI_FaceAnalysis
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI_InstantID
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-WD14-Tagger
   0.0 seconds (IMPORT FAILED): /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI_HF_Servelress_Inference
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI_SLK_joy_caption_two
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-IC-Light
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-TiledDiffusion
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-AutoCropFaces
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-inpaint-nodes
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-various
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI_essentials
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-Pets
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-KJNodes
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/rgthree-comfy
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/efficiency-nodes-comfyui
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI_UltimateSDUpscale
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/OneButtonPrompt
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-Advanced-ControlNet
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-GGUF
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui_controlnet_aux
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-Impact-Pack
   0.0 seconds (IMPORT FAILED): /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-art-venture
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI_LayerStyle
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/Comfyui_CXH_joy_caption
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui_segment_anything
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-tensorops
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/PuLID_ComfyUI
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-PuLID-Flux
   0.0 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-PuLID-Flux-Enhanced
   0.1 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-Easy-Use
   0.1 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-Manager
   0.1 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-Gemini
   0.1 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-SUPIR
   0.1 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-BrushNet
   0.2 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI-Crystools
   0.3 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/DZ-FaceDetailer
   0.3 seconds (IMPORT FAILED): /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/ComfyUI_Custom_Nodes_AlekPet
   0.5 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/was-node-suite-comfyui
   0.8 seconds (IMPORT FAILED): /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-reactor-node
   0.9 seconds: /Volumes/SSD 980 1TB/stable-diffusion-comfyui/custom_nodes/comfyui-mixlab-nodes

Starting server

To see the GUI go to: http://127.0.0.1:8188

**Comment by AlekPet** [comment]
> 重新 git clone 之后就可以了。Just re-git clone it.
> https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/91#issuecomment-2453026215
> https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/tree/new_init_config_disabled
> 
> 

This branch (is experimental) (https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/94) is needed to be able to disable unnecessary nodes, the **__init__.py** file was changed there and the config.json file was added. So check if the "check_enabled_nodes" parameter in config.json is false, then the filter for disabling will not work for everyone and all nodes will be loaded, if true, then the disabling rules come into play, either for all folders (the active parameter), or if false is set for certain nodes in the nodes > node_name parameter. And so you can also replace the **__init_.py** file from master if you don't need it at all. Maybe there are some other errors in the console?

**Comment by hoonkies** [comment]
> > 重新 git clone 之后就可以了。重新 git clone 就可以了。
> > [#91（评论）](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/91#issuecomment-2453026215)
> > https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/tree/new_init_config_disabled
> 
> 需要此分支（实验性的）（#94）才能禁用不必要的节点，`__init__.py`文件在那里进行了更改，并添加了 config.json 文件。因此，请检查 config.json 中的“check_enabled_nodes”参数是否为 false，然后禁用过滤器将不适用于所有人，并且将加载所有节点，如果为 true，则禁用规则将生效，无论是针对所有文件夹（active 参数），还是在 nodes > node_name 参数中为某些节点设置 false。因此，`__init_.py`如果您根本不需要它，也可以从 master 替换文件。检查 DeepTranslator 文件夹中的 python 文件是否已设置 :)。也许控制台中还有其他错误？

<img width="444" alt="image" src="https://github.com/user-attachments/assets/0459a602-b276-4239-9041-f2d5b7336af6">

Yes, I found that the left interface of the node is missing.

**Comment by hoonkies** [comment]
> > 重新 git clone 之后就可以了。Just re-git clone it.
> > [#91 (comment)](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/91#issuecomment-2453026215)
> > https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/tree/new_init_config_disabled
> 
> This branch (is experimental) (#94) is needed to be able to disable unnecessary nodes, the `__init__.py` file was changed there and the config.json file was added. So check if the "check_enabled_nodes" parameter in config.json is false, then the filter for disabling will not work for everyone and all nodes will be loaded, if true, then the disabling rules come into play, either for all folders (the active parameter), or if false is set for certain nodes in the nodes > node_name parameter. And so you can also replace the `__init_.py` file from master if you don't need it at all. Check in DeepTranslator folder python file isset :). Maybe there are some other errors in the console?

Thank you. When I put the modified __init_.py in the previous node folder, alekpet can also be used normally.

**Comment by AlekPet** [comment]
Logically, it should have pulled data from config.json
`__init__.py`
```py
        # Global settings
        if GLOBAL_SETTINGS is not None:
            is_check_enabled_nodes = GLOBAL_SETTINGS.get(
                "check_enabled_nodes", True)
```

File `config.json`
```json
"global_settings": {
    "check_enabled_nodes": false
  }
```

**Comment by hoonkies** [comment]
> ```json
> "global_settings": {
>     "check_enabled_nodes": false
>   }
> ```

I followed this method and changed is_check_enabled_nodes in _init.py back to true.

Config settings --
is_check_enabled_nodes = true

At the same time, I changed global_settings check_enabled_nodes in config.json to true.

"global_settings": {
"check_enabled_nodes": false
}

AlekPet also works properly.
