### ISSUE TITLE
(IMPORT FAILED) error occured

### ISSUE THREAD

**Issue by maiqunshan** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#95]
Traceback (most recent call last):
  File "C:\ComfyUI_MAI\ComfyUI\nodes.py", line 2024, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_MAI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet-master\__init__.py", line 185, in <module>
    installNodes()
  File "C:\ComfyUI_MAI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet-master\__init__.py", line 181, in installNodes
    addComfyUINodesToMapping(nodeElement)
  File "C:\ComfyUI_MAI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet-master\__init__.py", line 129, in addComfyUINodesToMapping
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_MAI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet-master\TranslateNode\translate_node.py", line 2, in <module>
    from googletrans import Translator, LANGUAGES
  File "C:\ComfyUI_MAI\python_embeded\Lib\site-packages\googletrans\__init__.py", line 6, in <module>
    from googletrans.client import Translator
  File "C:\ComfyUI_MAI\python_embeded\Lib\site-packages\googletrans\client.py", line 25, in <module>
    class Translator:
  File "C:\ComfyUI_MAI\python_embeded\Lib\site-packages\googletrans\client.py", line 55, in Translator
    proxies: typing.Dict[str, httpcore.SyncHTTPTransport] = None, timeout: Timeout = None):
AttributeError: module 'httpcore' has no attribute 'SyncHTTPTransport'

Cannot import C:\ComfyUI_MAI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet-master module for custom nodes: module 'httpcore' has no attribute 'SyncHTTPTransport'

How to solve it？

**Comment by AlekPet** [comment]
Hello! Usied this my comment https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/93#issuecomment-2488299156 , run shell in the your direvtory (`C:\ComfyUI_MAI\`) or inside comfyu manager pip commands.
Updgrade or uninstall and install:
```python
pip unstall googletrans
pip install googletrans==4.0.0-rc1
```
or 
```python
pip install googletrans --upgrade
```

Also: https://stackoverflow.com/a/73005547/23512000

**Comment by maiqunshan** [comment]
Following your method, the problem was solved, but a new problem arose. "comfyui-supir" went wrong and there was a dependency conflict. I don't know what to do? Thank you

**Comment by AlekPet** [comment]
You can try to install the old version, I don't know if it works. `googletrans==3.1.0a0`. Or find the file C:\ComfyUI_MAI\python_embeded\Lib\site-packages\httpcore\client.py and replace `httpcore.SyncHTTPTransport` to `httpcore.AsyncHTTPProxy` how write this  https://stackoverflow.com/a/73005547/23512000

**Comment by AlekPet** [comment]
> I can't solve it, I can only give up one of them

Or used this my branch https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/93#issuecomment-2480928680 `__init__.py` and config.json, disable googletranlate only nodes. 😉

**Comment by maiqunshan** [comment]
ok,thanks

**Comment by AlekPet** [comment]
Hi, too many logs. Error this:
```FileNotFoundError: [Errno 2] No such file or directory: 'K:\comfyUI 课程和模型\ComfyUI-aki-v1.3\custom_nodes\argos-translate\init.py'```
You don't have my folder Comfyu_Custom_Nodes_Alekpet, where the init.py file for installing nodes is located

**Comment by zy4908** [comment]
thanks for your help ，i will try that，but when i install that ，i have a file folder （argos-translate ）and（comfui nodes alekpet）already under custom nodes，so not sure why and how to fix，i still need translate，so how can fix that

**Comment by zy4908** [comment]
thanks fixed ，good to go
